blueprint:
  name: Cast to Google Home Hub
  description: Casting lovelace view to a Google Home Hub. Then every predefined time, check if the dashboard is being shown.
  domain: automation
  input:
    media_player:
      name: Google Device
      description: Google Hub/TV/Chromecast device to cast to
      selector:
        entity:
          domain: media_player
    dashboard_path:
      name: Lovelace dashboard
      description: Path to lovelace. Defaults to 'lovelace' if empty.
      default: lovelace
    dashboard_view:
      name: Lovelace view
      description: Path of the view to cast. A path has to be defined in your Lovelace
        YAML for each view, as outlined in the views documentation.
      default: default_view
    dashboard_name:
      name: Lovelace dashboard Name
      description: Listed within state of the casted device within Developer Tools
    wait_time:
      name: Wait time
      description: Time to check if the dashboard is being show. (Default 600 seconds)
      default: 600
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    start_time:
      name: Start trigger
      description: When do you want the dashboard to start casting
      selector:
        time:
    stop_time:
      name: End trigger
      description: When do you want the dashboard to stop casting
      selector:
        time:
        
mode: restart
max_exceeded: silent

variables:
  selected_player: !input media_player  # Variable to hold the selected media player entity
  selected_dashboard_name: !input dashboard_name
  start_time: !input start_time
  stop_time: !input stop_time

trigger:
  - platform: state
    entity_id: !input 'media_player'
    to: 'off'
    for: 00:10:00
  - platform: state
    entity_id: !input 'media_player'
    to: 'idle'
    for: 00:10:00
  - trigger: time_pattern
    minutes: /10
  - trigger: time
    at: !input 'stop_time'
    id: stop_casting
  
action:
  - if:
      - condition: and
        conditions:
          - condition: time
            after: !input 'start_time'
            before: !input 'stop_time'
          - condition: or
            conditions:
              - condition: state
                entity_id: !input 'media_player'
                state: 'off'
              - condition: state
                entity_id: !input 'media_player'
                state: 'idle'
    then:
      - action: media_player.volume_mute
        metadata: {}
        data:
          is_volume_muted: true
        target:
          entity_id: !input 'media_player'
      - action: media_player.turn_off
        target:
          entity_id: !input 'media_player'
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - action: cast.show_lovelace_view
        metadata: {}
        data:
          dashboard_path: !input 'dashboard_path'
          view_path: !input 'dashboard_view'
          entity_id: !input 'media_player'
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - action: media_player.volume_mute
        metadata: {}
        data:
          is_volume_muted: false
        target:
          entity_id: !input 'media_player'
  - if:
      - condition: and
        conditions:
          - condition: time
            after: !input 'start_time'
            before: !input 'stop_time'
          - condition: template
            value_template: >
              {{ 'Home Assistant Lovelace' in state_attr(selected_player, 'app_name') }}
          - condition: not
            conditions:
              - condition: template
                value_template: >
                  {{ selected_dashboard_name in state_attr(selected_player, 'media_title') }}
    then:
      - action: media_player.volume_mute
        metadata: {}
        data:
          is_volume_muted: true
        target:
          entity_id: !input 'media_player'
      - action: media_player.turn_off
        target:
          entity_id: !input 'media_player'
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - action: cast.show_lovelace_view
        metadata: {}
        data:
          dashboard_path: !input 'dashboard_path'
          view_path: !input 'dashboard_view'
          entity_id: !input 'media_player'
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - action: media_player.volume_mute
        metadata: {}
        data:
          is_volume_muted: false
        target:
          entity_id: !input 'media_player'
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id:
              - stop_casting
          - condition: and
            conditions:
              - condition: time
                after: !input 'stop_time'
              - condition: template
                value_template: >
                  {{ 'Home Assistant Lovelace' in state_attr(selected_player, 'app_name') }}
          - condition: and
            conditions:
              - condition: time
                before: !input 'start_time'
              - condition: template
                value_template: >
                  {{ 'Home Assistant Lovelace' in state_attr(selected_player, 'app_name') }}
    then:
      - action: media_player.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: !input 'media_player'